stages:
- test

test:
  stage: test
  visible: true
  image: mcr.microsoft.com/dotnet/sdk:7.0.100
  script:
  - dotnet restore
  - dotnet test --verbosity normal
  artifacts:
    paths:
    - TestResults/
